# Generated by Django 5.1.3 on 2025-01-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village', models.CharField(max_length=100)),
                ('parish', models.CharField(max_length=100)),
                ('subcounty', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('country', models.CharField(default='Uganda', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Locations',
            },
        ),
    ]
