# Generated by Django 5.1.5 on 2025-01-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Land Transfer',
                'verbose_name_plural': 'Land Transfers',
                'ordering': ['-transfer_date'],
            },
        ),
    ]
