# Generated by Django 5.1.3 on 2025-01-27 13:36

import property.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='title_document',
            field=models.FileField(help_text='Upload land title documents (PDF, image, or docx files).', upload_to='land_titles/', validators=[property.models.validate_file_type]),
        ),
    ]
